// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDLVVlKM1pitfi04be3iSN_wAaA_GN9_po',
    appId: '1:1024911455249:web:5d2a3fd301059595426db0',
    messagingSenderId: '1024911455249',
    projectId: 'csc4360-activity15-firebase',
    authDomain: 'csc4360-activity15-firebase.firebaseapp.com',
    storageBucket: 'csc4360-activity15-firebase.firebasestorage.app',
    measurementId: 'G-3KN5SG7943',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBUmty-o2OvKk351tmBPfGneV1Lg2tVnkw',
    appId: '1:1024911455249:android:7a1668d756228192426db0',
    messagingSenderId: '1024911455249',
    projectId: 'csc4360-activity15-firebase',
    storageBucket: 'csc4360-activity15-firebase.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAhQlpSC11VL-7iL7jf_VHKFIpEipsSJ7o',
    appId: '1:1024911455249:ios:337c4c59900c18c9426db0',
    messagingSenderId: '1024911455249',
    projectId: 'csc4360-activity15-firebase',
    storageBucket: 'csc4360-activity15-firebase.firebasestorage.app',
    iosBundleId: 'com.example.firebasedemo',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAhQlpSC11VL-7iL7jf_VHKFIpEipsSJ7o',
    appId: '1:1024911455249:ios:337c4c59900c18c9426db0',
    messagingSenderId: '1024911455249',
    projectId: 'csc4360-activity15-firebase',
    storageBucket: 'csc4360-activity15-firebase.firebasestorage.app',
    iosBundleId: 'com.example.firebasedemo',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDLVVlKM1pitfi04be3iSN_wAaA_GN9_po',
    appId: '1:1024911455249:web:7513b0dbff200d58426db0',
    messagingSenderId: '1024911455249',
    projectId: 'csc4360-activity15-firebase',
    authDomain: 'csc4360-activity15-firebase.firebaseapp.com',
    storageBucket: 'csc4360-activity15-firebase.firebasestorage.app',
    measurementId: 'G-Q8908SPKVH',
  );
}
